[tool.poetry]
name = "comm-dec"
version = "0.1.0"
description = ""
authors = ["reyan1357 <singhhimangshu20@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
